import os
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from typing import TypedDict,Annotated,Sequence
from langchain_core.messages import HumanMessage,BaseMessage,AIMessage,ToolMessage,SystemMessage
from langchain_core.tools import tool
from langgraph.prebuilt import ToolNode
from operator import add
from langchain_google_genai import ChatGoogleGenerativeAI
from dotenv import load_dotenv

from Supervisor.supervisor_sys import load_system_prompt

load_dotenv()
@tool
def code_query(problem:str):
    """
    this node extrcts the query from the user input and returns the code input
    :param problem:
    :return:
    """
    return problem

class MsgIns(TypedDict):
    role:str
    content:str

class AgentState(TypedDict):
    messages:list[MsgIns]
    user_message:str
    intent:str
    complexity:str
    test_status:bool
    agent_stat:str
    status:str
    name:str

llm = ChatGoogleGenerativeAI.supervisor_llm(model = "gemini-2.5-flash-lite",
                                                       google_api_key = os.getenv("GOOGLE_API_KEY"),
                                                       temperature  = 0)

@tool
def file_operations(intent:str,name:str):
    status = False
    return status

def Supervisor_Node(state:AgentState):
    """"
    This node helps differentiate between weather the query is a coding, research, or normal llm query
    """
    if state["intent"] == None:
        response = llm.invoke([SystemMessage(content = load_system_prompt("Supervisor/supervisor.txt")),
                              HumanMessage(content = state["user_message"])])
        line1 ,line2 = response.content.split("\n")
        key1,value1 = line1.strip.split(":")
        key2,value2 = line2.strip.split(":")
        state[key1.strip()] = value1.strip()
        state[key2.strip()] = value2.strip()
        state["messages"].append({
            "role":"user",
            "content":state["user_message"],
        })
        state["messages"].append({
            "role":"supervisor",
            "content":response.content,
        })
    return state


def Router(state:AgentState):
    """
    Decides what Agent to call based on the intent generated by the Supervisor Node
    :param state:
    :return:
    """
    if state["intent"] == "code_generation":
        if state["complexity"] == "simple":
            return "coding_agent"
        else:
            return "research_agent"
    elif state["intent"] == "testing":
        if state["complexity"] == "simple":
            return "testing_agent"
        else:
            return "research_agent"
    elif state["intent"] == "research":
        return "research_agent"
    else:
        return "normal_chat"


def Coder_Node(state:AgentState):
    coder_sys_prompt = load_system_prompt("Coder/coder.txt")
    response = llm.invoke([SystemMessage(content=load_system_prompt("Supervisor/supervisor.txt")),
                           HumanMessage(content=state["user_message"])])
    response = response.content.strip()
    response = response.split(",")
    solution = ""
    if response[0] not in ['generate_code','create_file','edit_code','rename_file','write_code','delete_file','testing']:
        state['name'] = response[0]
    for instruct in response:
        if instruct == 'generate_code':
            if state["name"] != "" and solution != "":
        if instruct == 'create_file':
    state["intent"] = "testing"
    return state



graph = StateGraph(AgentState)
graph.add_node("supervisor",Supervisor_Node)
graph.add_node("coder",Coder_Node)
graph.add_edge(START,"supervisor")
graph.add_edge("supervisor","coder")
graph.add_edge("coder","supervisor")